# Generated by Django 3.1.7 on 2021-04-21 17:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_text', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinputdata',
            name='text_body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
